export const blogsData = [
    {
        id:1,
        title: "Html",
        body: "Html Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet dolore doloribus eligendi illo modi non, odio quae ut! Autem ea esse ipsam omnis saepe? Cumque dolor eius facilis quidem quisquam totam veniam voluptates voluptatum? Blanditiis ex fuga fugit impedit inventore iure laboriosam modi necessitatibus, nesciunt officiis, optio praesentium quaerat quos ratione repudiandae sequi sunt temporibus unde ut veniam vero voluptatem voluptatum. Animi aspernatur blanditiis consequuntur fugit ipsam iste laborum officiis quia quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis?"
    },{
        id:2,
        title: "React",
        body: "React Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet dolore doloribus eligendi illo modi non, odio quae ut! Autem ea esse ipsam omnis saepe? Cumque dolor eius facilis quidem quisquam totam veniam voluptates voluptatum? Blanditiis ex fuga fugit impedit inventore iure laboriosam modi necessitatibus, nesciunt officiis, optio praesentium quaerat quos ratione repudiandae sequi sunt temporibus unde ut veniam vero voluptatem voluptatum. Animi aspernatur blanditiis consequuntur fugit ipsam iste laborum officiis quia quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis?"
    },{
        id:3,
        title: "CSS",
        body: "Css Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet dolore doloribus eligendi illo modi non, odio quae ut! Autem ea esse ipsam omnis saepe? Cumque dolor eius facilis quidem quisquam totam veniam voluptates voluptatum? Blanditiis ex fuga fugit impedit inventore iure laboriosam modi necessitatibus, nesciunt officiis, optio praesentium quaerat quos ratione repudiandae sequi sunt temporibus unde ut veniam vero voluptatem voluptatum. Animi aspernatur blanditiis consequuntur fugit ipsam iste laborum officiis quia quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis?"
    },{
        id:4,
        title: "Php",
        body: "Php Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet dolore doloribus eligendi illo modi non, odio quae ut! Autem ea esse ipsam omnis saepe? Cumque dolor eius facilis quidem quisquam totam veniam voluptates voluptatum? Blanditiis ex fuga fugit impedit inventore iure laboriosam modi necessitatibus, nesciunt officiis, optio praesentium quaerat quos ratione repudiandae sequi sunt temporibus unde ut veniam vero voluptatem voluptatum. Animi aspernatur blanditiis consequuntur fugit ipsam iste laborum officiis quia quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis quod sapiente! Amet animi, asperiores cumque debitis deleniti dolore ducimus earum eius explicabo facere fugiat harum, iste maxime non odio placeat qui repellendus rerum, saepe tempore? Qui, repudiandae, veritatis?"
    }  
];